### ISSUE TITLE
Multi-metric packets support

### ISSUE THREAD

**Issue by graineri** [wayfair/statsdcc#4]
Are you planning to support multi-metric packets?

**Comment by sdomalap** [comment]
@graineri, statsdcc supports multi-metric packets.
Just separate each metric in a packet with a newline character. 
```metric1:1|c\nmetric2:1|ms\nmetric3:32|g```

**Comment by graineri** [comment]
We are already doing so but we are losing lots of metrics (*), so I took a really quick look at the code and couldn't find the place where it's actually parsing the '\n'.

(*) We are getting "Bad Lines" logs due to an apparent invalid format (missing metric type. E.g. "Bad line: metric-name.bleh.1888.roi:0.17".). 

I ran tcpdump in order to see what statsdcc is receiving and it seems to be OK.

This is weird since we are using statsD in production without issues but need to scale it. Hence, we are planning to use statsdcc.

**Comment by draco2003** [comment]
Can you show us the tcpdump of the metrics your application sent? That
would be helpful in troubleshooting.

**Comment by graineri** [comment]
[UDP_Packet.txt](https://github.com/wayfair/statsdcc/files/1303442/UDP_Packet.txt)

**Comment by sdomalap** [comment]
Here is the line of code that splits the metrics.
https://github.com/wayfair/statsdcc/blob/master/lib/net/servers/socket/udp_server.cc#L110

let me take a look at the tcpdump.

**Comment by draco2003** [comment]
Possible to get a bad line example for that tcpdump? or a tcpdump that you
got the bad line from?
Does this packet represent one that failed? The packet you sent from a
quick look doesn't seem like it would cause errors or have bad metrics
based on the size and completeness of the metric names/data at the end of
the packet.

What we've seen in the past was if we put to many metrics in one metric
flush it gets split across multiple packets.
Our client side code auto flushes/auto splits large metric payloads into
appropriate sized payloads for one packet

**Comment by graineri** [comment]
I cannot assure that the dump I sent contains errors. It's quite difficult to get one dump that actually caused a Bad Line, unless I log it somewhere in the code.

We are using a packet size large enough to fit in our network's MTU so that we avoid packet split.

**Comment by draco2003** [comment]
@sdomalap is going to confirm and test, but it looks like an initial buffer
size is much lower than it should be.

If you have a chance to try setting this to your MTU size and verify that
would be great:
https://github.com/wayfair/statsdcc/blob/master/include/statsdcc/net/servers/socket/server.h#L16

**Comment by sdomalap** [comment]
@graineri, we have a very low buffer size set in the code. That might be truncating the metrics list.
https://github.com/wayfair/statsdcc/blob/master/include/statsdcc/net/servers/socket/server.h#L16

We are working on rolling out a fix.
For your testing, you can simply increase the number and re-compile. 

Feel free to make a pull request if you get to it first.

**Comment by graineri** [comment]
Awesome. Let me try that out and I'll get back to you.

**Comment by graineri** [comment]
OK. That fixed the issue. I set that constant to a value of 10000 and I'm no longer seeing Bad Lines.

**Comment by draco2003** [comment]
Glad to hear it. Thanks for testing and getting back to us. Nice catch!

-Dan

**Comment by sdomalap** [comment]
fixed in https://github.com/wayfair/statsdcc/commit/a2e637525ba49cc7608145b1a9b203ec03cc3308
