### ISSUE TITLE
Metrics take too long to show up

### ISSUE THREAD

**Issue by graineri** [wayfair/statsdcc#5]
It seems that metrics take up to 3 minutes to show up in Grafana (which is rendering from Graphite/Carbon). 

I tried configuring different flush frequencies (60 seconds, 30 seconds, 10 seconds and 1 second). I have also tried several worker and UDP thread count without luck.

Our current production metrics obtained from StatsD are rendered every minute without any further lag.

**Comment by sdomalap** [comment]
@graineri, can you confirm that lag is from statsdcc?
One way to check is running tcpdump and sniff for out going tcp stream from statsdcc box.

The aggregator should flush at every flush interval. So if you have 10 sec flush interval the data should go out every 10 secs.

**Comment by graineri** [comment]
I ran tcpdump and metrics are effectively and constantly going out, but I noticed that the metrics had an additional and unnecessary dot after the prefix: `stats..metric.bleh.blah`. 

So, I checked the configuration and confirmed that I had set `stats.` as the prefix. So, I removed that additional dot and everything's working fine now.

Thanks for all your quick responses.
