### ISSUE TITLE
Metrics drop

### ISSUE THREAD

**Issue by graineri** [wayfair/statsdcc#6]
I have just setup a statsdcc-proxy with two statsdcc-aggregators and one carbon backend.

After doing this, the metrics dropped to nearly a quarter as they used to be when I had a single statsdcc-aggregator. 

I guess that the proxy is hashing the metric so that the same metric is always received by the same statsdcc-aggregator. So, that shouldn't be a problem.

It also seems that I'm losing metrics from certain application nodes that I used to have before adding the proxy.

Any ideas why I'm facing this behavior?

**Comment by sdomalap** [comment]
Proxy does calculate integer hash of the metric name. It's some processing in the order of length of metric names.

You can scale proxy by increasing the number of worker threads.

Are you running all of them on the same host? How is your CPU utilization look?

**Comment by graineri** [comment]
I'm running each of them on separate instances. Each instance has 4 cores and are quite idle in terms of processing. So, that should be fine.

**Comment by graineri** [comment]
I might be using the original code without the MSG_SIZE fix. Let me check everything and get back to you.

**Comment by graineri** [comment]
False alarm. Totally my fault. I was using the previous version without the fix. I'm sorry about this.
