### ISSUE TITLE
Proxy tuning

### ISSUE THREAD

**Issue by graineri** [wayfair/statsdcc#7]
Workers' queues are filling up and proxy starts dropping metrics. I tried increasing the amount of workers but needed 2048 workers to stop dropping metrics but this doesn't sound like the correct approach (besides CPU usage goes to 100%)

I have also tried increasing Boost's lock free queue to 65000 instead of 10000 (I noticed there's a TODO in the code as well) without luck. Is it possible to leave the queue without a fixed size?

I am also noticing a high system CPU usage (which I don't see in aggregator mode).

How do you guys tune this in production?

**Comment by sdomalap** [comment]
@graineri, there are two ways you can scale proxy.

1. Increasing number of worker threads. You have already tried this.
2. Running multiple proxies.

If you use the second approach and run multiple instances, then you need a way to distribute the metrics across these instances.
There are three ways we do it in our production.

1. Make applications distribute the load. We publish the list of IPs of the proxies to the applications, and applications either round robin the list or randomly pick an item from the list. 
2. Use Round Robin DNS entry. A DNS entry that resolves to different IPs in the list, in RR fashion.
3. Use a lightweight load balancer. We have extended statsdcc to load balance the metrics across proxies. It's lighter than proxy as it does not have to hash. The real use of that application was to duplicate metrics across different data stores (For example, to duplicate production metrics to our test environments). We have not open sourced that project yet. 
You can use [Nginx udp load balancer](https://www.nginx.com/blog/announcing-udp-load-balancing/). It's easy to setup and we do use this in our production for other uses.

If you use option 3 you still might have to use option 1 or 2 depending on your production load. There is only so much a single instance of anything can handle.

**Comment by graineri** [comment]
Thanks for your reply. 

I have considered all those alternatives before but I reckoned that statsdcc-proxy would be able to handle our load with a single instance. I mean it's just hashing and re-sending. 

Taking a look at the aggregator loads (we have two) I would also be tempted to say that one aggregator would be able to handle all of our load, but that's not what we want since it will start being a bottleneck soon.

Anyway, for the time being, I guess I will add more proxies (probably more proxies than aggregators, which really sounds odd) and put them behind a load balancer.

**Comment by sdomalap** [comment]
@graineri, just making sure. You are not using blacklist feature right?
https://github.com/wayfair/statsdcc/blob/master/etc/proxy.json#L22

That can significantly slow down the proxy as it has run regex match against every single metric.
https://github.com/wayfair/statsdcc/blob/master/src/workers/proxy/worker.cc#L83

Make sure you you drop that setting in your config.

**Comment by graineri** [comment]
Correct. I'm not using that feature.

**Comment by sdomalap** [comment]
@graineri, I think I know where the bottle neck might be. You might have to increase the number of udp server threads. Given that you are sending milti metric packets. The server thread had to do some processing to split them into individual metrics.

**Comment by graineri** [comment]
I tried that without luck. Honestly, I was kind of expecting it since the issue is that workers' queues are filling up. This means that metrics are coming at a faster pace than the workers can handle.

UDP threads are the ones pushing metrics to the workers, so adding UDP threads won't help.

Do you guys know if Boost's lock-free queue can be configured without a fixed-size? Of course, if workers are not able to handle all the load this won't solve the issue, but at least we can enqueue metrics with more freedom to see if that helps the worker to relieve their load.

**Comment by sdomalap** [comment]
As you said increasing the queue size does not matter if the workers can't keep up.

I don't know much about your metric naming scheme. Maybe you can try optimizing the hashing specific to your case.

**Comment by sdomalap** [comment]
@graineri, at what rate the proxies are consuming in your setup?
How many proxies are you running?

**Comment by graineri** [comment]
@sdomalap, according to `iptraf`, we are receiving ~5K UDP packets per second, each of them of size ~8Kb.

We are currently using 4 statsdcc-proxies behind an nginx.
